cases:
  example:
    item: "minecraft:stick"
    regex: "(?i)example regex.*"
    model: "minecraft:torch"
    custom_model_data: false
  example2:
    item: "minecraft:iron_ingot"
    regex: "(?i)example regex.*"
    model: "minecraft:torch"
    custom_model_data: true